# .gitlab-ci.yml edited

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building Spring Boot application..."
  tags:
    - pipe-petclinic-runner

test:
  stage: test
  script:
    - echo "Running tests for Spring Boot application..."
  tags:
    - pipe-petclinic-runner

deploy:
  stage: deploy
  script:
    - echo "Deploying Spring Boot application..."
  tags:
    - pipe-petclinic-runner
