variables:
  DOCKER_USERNAME: "bassel10"
  DOCKER_PASSWORD: "wassim123"

stages:
  - build
  - dockerize
  - deploy

build:
  stage: build
  image: maven:3.6.3-openjdk-17
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  tags:
    - pipe-petclinic-runner

dockerize:
  stage: dockerize
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - docker build -t $DOCKER_USERNAME/petclinic:latest .
    - docker push $DOCKER_USERNAME/petclinic:latest
  dependencies:
    - build
  tags:
    - docker-runner

deploy:
  stage: deploy
  image: docker/compose:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - docker-compose -f docker-compose.yml up -d
  tags:
    - docker-runner

