name: Mirror to GitLab

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitLab
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add gitlab git@gitlab.com:pfe20243/mirroringrepo.git
          git push gitlab main
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}

