name: Mirror to GitLab

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitLab
        run: |
          git config user.name bvssel
          git config user.email rachedwassim.bassel@effyis-partners.ma
          git remote add gitlab 'https://bvssel:${{ secrets.token }}@gitlab.com/pfe20243/mirroringrepo.git'
          git pull --rebase -X theirs gitlab main 
          git push --force gitlab HEAD:main
        env:
          token: ${{ secrets.token }}
