name: Mirror to GitLab

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitLab
        run: |
          git clone https://gitlab.com/pfe20243/mirroringrepo.git repo
          cd repo
          git config --global user.email "rachedwassim.bassel@effyis-partners.ma"
          git config --global user.username "bvssel"
          git push origin main
        env:
          GITLAB_TOKEN: ${{ secrets.MY_ACCESS_SECRET }}

