name: Mirror to GitLab

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitLab
        run: |
          git config user.email rachedwassim.bassel@effyis-partners.ma
          git config user.username bvssel
          git clone https://bvssel:$MY_ACCESS_SECRET_repo@gitlab.com/pfe20243/mirroringrepo.git
        env:
          EXTERNAL_TOKEN: ${{ secrets.MY_ACCESS_SECRET_repo }}
